import { franc } from "franc";

export const languageNameMap: { [key: string]: string } = {
  afr: "Afrikaans",
  sqi: "Albanian",
  amh: "Amharic",
  arb: "Arabic",
  hye: "Armenian",
  asm: "Assamese",
  aze: "Azerbaijani",
  eus: "Basque",
  bel: "Belarusian",
  ben: "Bengali",
  bos: "Bosnian",
  bul: "Bulgarian",
  mya: "Burmese",
  cat: "Catalan",
  ceb: "Cebuano",
  nya: "Chichewa",
  cmn: "Chinese",
  hrv: "Croatian",
  ces: "Czech",
  dan: "Danish",
  nld: "Dutch",
  eng: "English",
  epo: "Esperanto",
  est: "Estonian",
  fin: "Finnish",
  fra: "French",
  glg: "Galician",
  kat: "Georgian",
  deu: "German",
  ell: "Greek",
  guj: "Gujarati",
  hat: "Haitian Creole",
  hau: "Hausa",
  heb: "Hebrew",
  hin: "Hindi",
  hmn: "Hmong",
  hun: "Hungarian",
  isl: "Icelandic",
  ibo: "Igbo",
  ind: "Indonesian",
  gle: "Irish",
  ita: "Italian",
  jpn: "Japanese",
  jav: "Javanese",
  kan: "Kannada",
  kaz: "Kazakh",
  khm: "Khmer",
  kor: "Korean",
  kur: "Kurdish",
  kir: "Kyrgyz",
  lao: "Lao",
  lat: "Latin",
  lav: "Latvian",
  lit: "Lithuanian",
  ltz: "Luxembourgish",
  mkd: "Macedonian",
  mlg: "Malagasy",
  msa: "Malay",
  mal: "Malayalam",
  mlt: "Maltese",
  mri: "Maori",
  mar: "Marathi",
  mon: "Mongolian",
  nep: "Nepali",
  nor: "Norwegian",
  ori: "Odia",
  pus: "Pashto",
  prs: "Persian",
  pol: "Polish",
  por: "Portuguese",
  pan: "Punjabi",
  ron: "Romanian",
  rus: "Russian",
  smo: "Samoan",
  gla: "Scots Gaelic",
  srp: "Serbian",
  sna: "Shona",
  sin: "Sinhala",
  slk: "Slovak",
  slv: "Slovenian",
  som: "Somali",
  spa: "Spanish",
  sun: "Sundanese",
  swa: "Swahili",
  swe: "Swedish",
  tgl: "Tagalog",
  tgk: "Tajik",
  tam: "Tamil",
  tat: "Tatar",
  tel: "Telugu",
  tha: "Thai",
  tur: "Turkish",
  ukr: "Ukrainian",
  urd: "Urdu",
  uig: "Uyghur",
  uzb: "Uzbek",
  vie: "Vietnamese",
  cym: "Welsh",
  xho: "Xhosa",
  yid: "Yiddish",
  yor: "Yoruba",
  zul: "Zulu",
};

export function detectLanguage(text: string): string {
  const detectedLang = franc(text);
  console.log("Franc detected:", detectedLang);
  return languageNameMap[detectedLang] || "English"; // Default to English if not found
}
